### PR TITLE
Update codius-install.sh

### PR DESCRIPTION
**Pull request by TahiG**
Some grammatical and spelling improvements to help users understand instructions.

### CODE REVIEW

**Comment by jonaagenilsen** [comment]
> Some grammatical and spelling improvements to help users understand instructions.

Awesome! Maybe throw in info like "While waiting for DNS-records to be verified, test with command: nslookup -type=txt _acme-challenge.YOUDOMAIN.COM"?

**Comment by TahiG** [comment]
I’m new to this but happy to help. I’m a user experience writer so I specialise in optimising copy for user understanding. 

If you tell me where the above should go I’ll jump in, tweak it slightly and commit it.

**Comment by TahiG** [comment]
@jonaagenilsen I'm assuming it should go somewhere between line 533 and 550.

**Comment by TahiG** [comment]
Thanks @N3TC4T for merging. Will continue with the edit to make it as good as it can be. Will comment here when done.

**Comment by TahiG** [comment]
On lines 535 and 878 it would be good to give the user an estimate of how long they should wait after creating DNS records. We could say 30 minutes to be on the safe side.

**Comment by N3TC4T** [comment]
Thanks for your contribution , the other pull request just merged .

and yeah I believe we can do it's in an automate way and check every 10 sec to see if user added the TXT records then we move to another step .

**Comment by TahiG** [comment]
OK thanks, I'll go ahead and tell the user to wait 30 seconds.

**Pull request merged**
